/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mirror;

/**
 *
 * @author laura
 */
public class MirrorFrame extends javax.swing.JFrame {

    /**
     * Creates new form MirrorFrame
     */
    public MirrorFrame() {
        initComponents();
        
        buttonGroup1.add(this.rb1Original);
        buttonGroup1.add(this.rb2Original);
        buttonGroup1.add(this.rb3Original);
        
        buttonGroup2.add(this.rb1Mirror);
        buttonGroup2.add(this.rb2Mirror);
        buttonGroup2.add(this.rb3Mirror);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rb1Original = new javax.swing.JRadioButton();
        rb2Original = new javax.swing.JRadioButton();
        rb3Original = new javax.swing.JRadioButton();
        cb1Original = new javax.swing.JCheckBox();
        cb2Original = new javax.swing.JCheckBox();
        cb3Original = new javax.swing.JCheckBox();
        txtOriginal = new javax.swing.JTextField();
        cmbOriginal = new javax.swing.JComboBox<>();
        spnOriginal = new javax.swing.JSpinner();
        cmbMirror = new javax.swing.JComboBox<>();
        spnMirror = new javax.swing.JSpinner();
        txtMirror = new javax.swing.JTextField();
        rb1Mirror = new javax.swing.JRadioButton();
        rb2Mirror = new javax.swing.JRadioButton();
        rb3Mirror = new javax.swing.JRadioButton();
        cb1Mirror = new javax.swing.JCheckBox();
        cb2Mirror = new javax.swing.JCheckBox();
        cb3Mirror = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Original");

        jLabel2.setText("Mirror");

        rb1Original.setText("Option 1");
        rb1Original.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        rb1Original.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1OriginalActionPerformed(evt);
            }
        });

        rb2Original.setText("Option 2");
        rb2Original.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb2OriginalActionPerformed(evt);
            }
        });

        rb3Original.setText("Option 3");
        rb3Original.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb3OriginalActionPerformed(evt);
            }
        });

        cb1Original.setText("Option 4");
        cb1Original.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1OriginalActionPerformed(evt);
            }
        });

        cb2Original.setText("Option 5");
        cb2Original.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb2OriginalActionPerformed(evt);
            }
        });

        cb3Original.setText("Option 6");
        cb3Original.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb3OriginalActionPerformed(evt);
            }
        });

        txtOriginal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtOriginalKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtOriginalKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtOriginalKeyTyped(evt);
            }
        });

        cmbOriginal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbOriginal.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbOriginalItemStateChanged(evt);
            }
        });

        spnOriginal.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnOriginalStateChanged(evt);
            }
        });

        cmbMirror.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbMirror.setEnabled(false);

        spnMirror.setEnabled(false);

        txtMirror.setEnabled(false);

        rb1Mirror.setText("Option 1");
        rb1Mirror.setEnabled(false);

        rb2Mirror.setText("Option 2");
        rb2Mirror.setEnabled(false);

        rb3Mirror.setText("Option 3");
        rb3Mirror.setEnabled(false);

        cb1Mirror.setText("Option 4");
        cb1Mirror.setEnabled(false);

        cb2Mirror.setText("Option 5");
        cb2Mirror.setEnabled(false);

        cb3Mirror.setText("Option 6");
        cb3Mirror.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(rb3Original)
                            .addGap(18, 18, 18)
                            .addComponent(cb3Original, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(spnOriginal))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(rb2Original)
                            .addGap(18, 18, 18)
                            .addComponent(cb2Original, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(cmbOriginal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(rb1Original)
                            .addGap(18, 18, 18)
                            .addComponent(cb1Original, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rb3Mirror)
                                .addGap(18, 18, 18)
                                .addComponent(cb3Mirror, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rb2Mirror)
                                .addGap(18, 18, 18)
                                .addComponent(cb2Mirror, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rb1Mirror)
                                .addGap(18, 18, 18)
                                .addComponent(cb1Mirror, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spnMirror)
                            .addComponent(cmbMirror, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtMirror, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb1Original)
                    .addComponent(cb1Original)
                    .addComponent(txtOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb2Original)
                    .addComponent(cb2Original)
                    .addComponent(cmbOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb3Original)
                    .addComponent(cb3Original)
                    .addComponent(spnOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtMirror, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(cmbMirror, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spnMirror, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb3Mirror)
                            .addComponent(rb3Mirror))
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rb1Mirror)
                            .addComponent(cb1Mirror))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rb2Mirror)
                            .addComponent(cb2Mirror))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rb1OriginalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1OriginalActionPerformed
        
        this.rb1Mirror.setSelected(this.rb1Original.isSelected());
    }//GEN-LAST:event_rb1OriginalActionPerformed

    private void rb2OriginalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb2OriginalActionPerformed
        this.rb2Mirror.setSelected(this.rb2Original.isSelected());
    }//GEN-LAST:event_rb2OriginalActionPerformed

    private void rb3OriginalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb3OriginalActionPerformed
        this.rb3Mirror.setSelected(this.rb3Original.isSelected());
    }//GEN-LAST:event_rb3OriginalActionPerformed

    private void cb1OriginalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1OriginalActionPerformed
        this.cb1Mirror.setSelected(this.cb1Original.isSelected());
    }//GEN-LAST:event_cb1OriginalActionPerformed

    private void cb2OriginalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb2OriginalActionPerformed
        this.cb2Mirror.setSelected(this.cb2Original.isSelected());
    }//GEN-LAST:event_cb2OriginalActionPerformed

    private void cb3OriginalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb3OriginalActionPerformed
        this.cb3Mirror.setSelected(this.cb3Original.isSelected());
    }//GEN-LAST:event_cb3OriginalActionPerformed

    private void txtOriginalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOriginalKeyTyped
        
    }//GEN-LAST:event_txtOriginalKeyTyped

    private void cmbOriginalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbOriginalItemStateChanged
        this.cmbMirror.setSelectedIndex(this.cmbOriginal.getSelectedIndex());
    }//GEN-LAST:event_cmbOriginalItemStateChanged

    private void spnOriginalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnOriginalStateChanged
        this.spnMirror.setValue((Integer)this.spnOriginal.getValue());
    }//GEN-LAST:event_spnOriginalStateChanged

    private void txtOriginalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOriginalKeyPressed
        
    }//GEN-LAST:event_txtOriginalKeyPressed

    private void txtOriginalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOriginalKeyReleased
        this.txtMirror.setText(this.txtOriginal.getText());
    }//GEN-LAST:event_txtOriginalKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MirrorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MirrorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MirrorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MirrorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MirrorFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JCheckBox cb1Mirror;
    private javax.swing.JCheckBox cb1Original;
    private javax.swing.JCheckBox cb2Mirror;
    private javax.swing.JCheckBox cb2Original;
    private javax.swing.JCheckBox cb3Mirror;
    private javax.swing.JCheckBox cb3Original;
    private javax.swing.JComboBox<String> cmbMirror;
    private javax.swing.JComboBox<String> cmbOriginal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton rb1Mirror;
    private javax.swing.JRadioButton rb1Original;
    private javax.swing.JRadioButton rb2Mirror;
    private javax.swing.JRadioButton rb2Original;
    private javax.swing.JRadioButton rb3Mirror;
    private javax.swing.JRadioButton rb3Original;
    private javax.swing.JSpinner spnMirror;
    private javax.swing.JSpinner spnOriginal;
    private javax.swing.JTextField txtMirror;
    private javax.swing.JTextField txtOriginal;
    // End of variables declaration//GEN-END:variables
}
